---
driver:
  name: ec2
  instance_type: t2.micro

transport:
  username: ubuntu

provisioner:
  name: shell

platforms:
  - name: ubuntu
    driver: 
      image_id: ami-082a5d4cb01ee3450
      region: us-east-1

verifier:
  name: inspec

suites:
- name: default